### ISSUE TITLE
2.3 release checklist

### ISSUE THREAD

**Issue by Holzhaus** [mixxxdj/manual#117]
We have some stuff to do before the 2.3 release.

- [ ] Document cue colors and palette editor/replace tool
- [ ] Document Intro/Outro cues
- [ ] Document AutoDJ changes
- [ ] Update all screenshots to new default theme
- [ ] Update the [Version History](https://mixxx.org/manual/latest/en/chapters/appendix.html#version-history)
- [ ] *... (feel free to edit this post and add more items)*

**Comment by ronso0** [comment]
Thanks for taking care of all this tediuous housekeeping! :+1:
